name: Verifiable Build
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  # Anchor 0.25.0 (latest) does not include x86_64 binary, use older version until resolved https://github.com/coral-xyz/anchor/issues/2076
  ANCHOR_CLI_VERSION: 0.24.2

jobs:
  build:
    name: Build Verifiable Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Anchor CLI
        run: |
          npm install -g @project-serum/anchor-cli@${{ env.ANCHOR_CLI_VERSION }}
          anchor --version
      - name: Verifiable Build
        run: |
          echo "APP_NAME=$(cargo metadata --no-deps --format-version 1 | jq --raw-output '.packages[0].name')" >> $GITHUB_ENV 
          anchor build --verifiable
          ls
      - name: Generate Checksum
        run: |
          echo "CHECKSUM=$(sha256sum ./target/verifiable/${{ env.APP_NAME }}.so | head -c 64)" >> $GITHUB_ENV